services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    image: devlopersabbir/server:${VERSION}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "9000:9000"

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    image: devlopersabbir/client:${VERSION}
    ports:
      - "8000:8000"
