name: Build & Test

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and Test All Apps and packages
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm globally for installing npm packages
        run: npm install -g pnpm
      - name: Install all dependencies from the root
        run: pnpm install
      - name: Build our all apps which is has on our apps directory and all packages
        run: pnpm run build
